name: "Build"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Build website"
        run: yarn build
